### ISSUE TITLE
Release Code

### ISSUE THREAD

**Issue by haoranD** [zijian-hu/SimPLE#1]
Hi, thanks for your excellent work.

When will you release your code?

Thanks

**Comment by zijian-hu** [comment]
Dear Haoran,

Thank you for your interest in our paper.

We are currently cleaning up our codebase and plan to release our code before CVPR 2021 (June 19th, 2021). Since our current progress is ahead of the schedule, we might be able to release the code in one or two weeks.

Best

**Comment by zimenglan-sysu-512** [comment]
hi @zijian-hu 
do u still have a plan to release the code?

**Comment by zijian-hu** [comment]
@haoranD @zimenglan-sysu-512 I am delighted to inform you that the code is released
